Repository Huskydog9988/Salve, pull requests merged in 2022-05, with the labels that each got.

#20 Sorting again
  package.json
  pages/meetings/info/[pid].tsx
  pages/meetings/list.tsx
  server/db/Student.ts
  server/main.ts
  src/MeetingTable.tsx
  src/MeetingsTable.tsx
  src/UserTable.tsx
  src/shared/editUser.d.ts
  yarn.lock
Labels: enhancement

#60 59 fix docker build
  .dockerignore
  .gitignore
  Dockerfile
  prisma/migrations/20220522015935_inital_migration/migration.sql
  prisma/migrations/migration_lock.toml
Labels: bug

#62 remove unused dependencies
  package.json
  pages/meetings/create.tsx
  pages/quagga.d.ts
  yarn.lock
Labels: dependencies

#46 Export data
  docs/CONTRIBUTING.md
  pages/meetings/info/[pid].tsx
  prisma/schema.prisma
  server/db/Meeting.ts
  server/db/Participant.ts
  src/MeetingTable.tsx
  src/MeetingsTable.tsx
  src/UserTable.tsx
  src/shared/exportOptions.ts
Labels: enhancement

#68 Fixed Page Size of UserTable
  pages/users/list.tsx
  src/UserTable.tsx
Labels: enhancement

#67 Revising Tables
  pages/users/list.tsx
  src/MeetingTable.tsx
  src/MeetingsTable.tsx
  src/UserTable.tsx
Labels: bug, enhancement
